-- fichaloop · Packs por gremio (OPCIONAL). REQUIERE haber ejecutado antes
-- reformas-catalogo.sql (usa sus artículos art_r_*). Idempotente.
-- Borrar: delete from partidas where id like 'pack_g_%';

insert into partidas (id, tenant_id, nombre, unidad, descripcion, componentes) values
  ('pack_g_fontaneria_bano','forgevia','Fontanería baño','ud','Pack por gremio: Fontanería baño.','[{"id":"c0","articuloId":"art_r_plato_de_ducha","cantidad":1},{"id":"c1","articuloId":"art_r_mampara","cantidad":1},{"id":"c2","articuloId":"art_r_valvula_desague_de_ducha","cantidad":1},{"id":"c3","articuloId":"art_r_griferia_de_ducha","cantidad":1},{"id":"c4","articuloId":"art_r_columna_o_conjunto_de_ducha","cantidad":1},{"id":"c5","articuloId":"art_r_inodoro","cantidad":1},{"id":"c6","articuloId":"art_r_mueble_de_lavabo","cantidad":1},{"id":"c7","articuloId":"art_r_lavabo","cantidad":1},{"id":"c8","articuloId":"art_r_grifo_de_lavabo","cantidad":1},{"id":"c9","articuloId":"art_r_sifon_y_valvula_de_lavabo","cantidad":1},{"id":"c10","articuloId":"art_r_tuberia_multicapa_ppr_y_accesorios","cantidad":1},{"id":"c11","articuloId":"art_r_tuberia_pvc_para_desagues_y_accesorios","cantidad":1},{"id":"c12","articuloId":"art_r_llaves_de_escuadra","cantidad":1},{"id":"c13","articuloId":"art_r_silicona_sanitaria","cantidad":1}]'::jsonb),
  ('pack_g_electricidad_bano','forgevia','Electricidad baño','ud','Pack por gremio: Electricidad baño.','[{"id":"c0","articuloId":"art_r_downlights_focos","cantidad":1},{"id":"c1","articuloId":"art_r_interruptores_y_mecanismos","cantidad":1},{"id":"c2","articuloId":"art_r_cableado_electrico","cantidad":1},{"id":"c3","articuloId":"art_r_tubo_corrugado","cantidad":1},{"id":"c4","articuloId":"art_r_cajas_electricas","cantidad":1},{"id":"c5","articuloId":"art_r_extractor_de_bano","cantidad":1}]'::jsonb),
  ('pack_g_fontaneria_cocina','forgevia','Fontanería cocina','ud','Pack por gremio: Fontanería cocina.','[{"id":"c0","articuloId":"art_r_fregadero","cantidad":1},{"id":"c1","articuloId":"art_r_grifo_de_cocina","cantidad":1},{"id":"c2","articuloId":"art_r_sifon_y_desague","cantidad":1},{"id":"c3","articuloId":"art_r_llaves_de_escuadra","cantidad":1},{"id":"c4","articuloId":"art_r_tuberias_de_agua_y_accesorios","cantidad":1},{"id":"c5","articuloId":"art_r_pvc_de_desague","cantidad":1},{"id":"c6","articuloId":"art_r_silicona","cantidad":1}]'::jsonb),
  ('pack_g_electricidad_cocina','forgevia','Electricidad cocina','ud','Pack por gremio: Electricidad cocina.','[{"id":"c0","articuloId":"art_r_enchufes","cantidad":1},{"id":"c1","articuloId":"art_r_interruptores","cantidad":1},{"id":"c2","articuloId":"art_r_cableado","cantidad":1},{"id":"c3","articuloId":"art_r_tubo_corrugado","cantidad":1},{"id":"c4","articuloId":"art_r_cajas_de_mecanismos","cantidad":1},{"id":"c5","articuloId":"art_r_cajas_de_derivacion","cantidad":1},{"id":"c6","articuloId":"art_r_protecciones_electricas","cantidad":1},{"id":"c7","articuloId":"art_r_iluminacion_de_techo","cantidad":1},{"id":"c8","articuloId":"art_r_iluminacion_bajo_muebles","cantidad":1}]'::jsonb),
  ('pack_g_pladur','forgevia','Pladur','ud','Pack por gremio: Pladur.','[{"id":"c0","articuloId":"art_r_placas_de_pladur","cantidad":1},{"id":"c1","articuloId":"art_r_pladur_hidrofugo","cantidad":1},{"id":"c2","articuloId":"art_r_perfileria","cantidad":1},{"id":"c3","articuloId":"art_r_perfileria_de_pladur","cantidad":1},{"id":"c4","articuloId":"art_r_tornilleria","cantidad":1},{"id":"c5","articuloId":"art_r_cintas_y_pastas_de_juntas","cantidad":1},{"id":"c6","articuloId":"art_r_masilla_y_cinta","cantidad":1},{"id":"c7","articuloId":"art_r_aislamiento_termico_acustico","cantidad":1}]'::jsonb),
  ('pack_g_pintura','forgevia','Pintura','ud','Pack por gremio: Pintura.','[{"id":"c0","articuloId":"art_r_pintura","cantidad":1},{"id":"c1","articuloId":"art_r_imprimacion","cantidad":1},{"id":"c2","articuloId":"art_r_masillas","cantidad":1},{"id":"c3","articuloId":"art_r_pintura_para_techo","cantidad":1}]'::jsonb),
  ('pack_g_alicatado_y_solado','forgevia','Alicatado y solado','ud','Pack por gremio: Alicatado y solado.','[{"id":"c0","articuloId":"art_r_alicatado_azulejo","cantidad":1},{"id":"c1","articuloId":"art_r_pavimento","cantidad":1},{"id":"c2","articuloId":"art_r_adhesivo_cementoso","cantidad":1},{"id":"c3","articuloId":"art_r_lechada_material_de_juntas","cantidad":1},{"id":"c4","articuloId":"art_r_perfiles_y_remates","cantidad":1},{"id":"c5","articuloId":"art_r_material_de_nivelacion","cantidad":1},{"id":"c6","articuloId":"art_r_material_de_rejuntado","cantidad":1},{"id":"c7","articuloId":"art_r_adhesivos","cantidad":1}]'::jsonb)
on conflict (id) do nothing;
