-- fichaloop · Librería de reformas (OPCIONAL) para FORGEVIA.
-- Artículos típicos (a precio 0, se rellenan con tus facturas) + packs por tipo
-- de obra, a partir del listado del cliente. Idempotente. Requiere presupuestos.sql.
-- Borrar: delete from partidas where id like 'pack_r_%'; delete from articulos where id like 'art_r_%';

insert into articulos (id, tenant_id, referencia, nombre, proveedor_id, categoria, unidad, coste) values
  ('art_r_plato_de_ducha','forgevia','','Plato de ducha',null,'material','ud',0),
  ('art_r_mampara','forgevia','','Mampara',null,'material','ud',0),
  ('art_r_valvula_desague_de_ducha','forgevia','','Válvula/desagüe de ducha',null,'material','ud',0),
  ('art_r_griferia_de_ducha','forgevia','','Grifería de ducha',null,'material','ud',0),
  ('art_r_columna_o_conjunto_de_ducha','forgevia','','Columna o conjunto de ducha',null,'material','ud',0),
  ('art_r_inodoro','forgevia','','Inodoro',null,'material','ud',0),
  ('art_r_mueble_de_lavabo','forgevia','','Mueble de lavabo',null,'material','ud',0),
  ('art_r_lavabo','forgevia','','Lavabo',null,'material','ud',0),
  ('art_r_grifo_de_lavabo','forgevia','','Grifo de lavabo',null,'material','ud',0),
  ('art_r_espejo','forgevia','','Espejo',null,'material','ud',0),
  ('art_r_sifon_y_valvula_de_lavabo','forgevia','','Sifón y válvula de lavabo',null,'material','ud',0),
  ('art_r_tuberia_multicapa_ppr_y_accesorios','forgevia','','Tubería multicapa/PPR y accesorios',null,'material','ml',0),
  ('art_r_tuberia_pvc_para_desagues_y_accesorios','forgevia','','Tubería PVC para desagües y accesorios',null,'material','ml',0),
  ('art_r_llaves_de_escuadra','forgevia','','Llaves de escuadra',null,'material','ud',0),
  ('art_r_alicatado_azulejo','forgevia','','Alicatado/azulejo',null,'material','m²',0),
  ('art_r_pavimento','forgevia','','Pavimento',null,'material','m²',0),
  ('art_r_adhesivo_cementoso','forgevia','','Adhesivo cementoso',null,'material','ud',0),
  ('art_r_mortero','forgevia','','Mortero',null,'material','ud',0),
  ('art_r_lechada_material_de_juntas','forgevia','','Lechada/material de juntas',null,'material','ud',0),
  ('art_r_sistema_de_impermeabilizacion','forgevia','','Sistema de impermeabilización',null,'material','ud',0),
  ('art_r_silicona_sanitaria','forgevia','','Silicona sanitaria',null,'material','ud',0),
  ('art_r_perfiles_y_remates','forgevia','','Perfiles y remates',null,'material','ud',0),
  ('art_r_pladur_hidrofugo','forgevia','','Pladur hidrófugo',null,'material','m²',0),
  ('art_r_perfileria_de_pladur','forgevia','','Perfilería de pladur',null,'material','m²',0),
  ('art_r_tornilleria','forgevia','','Tornillería',null,'material','ud',0),
  ('art_r_masilla_y_cinta','forgevia','','Masilla y cinta',null,'material','ud',0),
  ('art_r_downlights_focos','forgevia','','Downlights/focos',null,'material','ud',0),
  ('art_r_interruptores_y_mecanismos','forgevia','','Interruptores y mecanismos',null,'material','ud',0),
  ('art_r_cableado_electrico','forgevia','','Cableado eléctrico',null,'material','ml',0),
  ('art_r_tubo_corrugado','forgevia','','Tubo corrugado',null,'material','ml',0),
  ('art_r_cajas_electricas','forgevia','','Cajas eléctricas',null,'material','ud',0),
  ('art_r_extractor_de_bano','forgevia','','Extractor de baño',null,'material','ud',0),
  ('art_r_pintura_para_techo','forgevia','','Pintura para techo',null,'material','m²',0),
  ('art_r_muebles_bajos','forgevia','','Muebles bajos',null,'material','ud',0),
  ('art_r_muebles_altos','forgevia','','Muebles altos',null,'material','ud',0),
  ('art_r_columnas','forgevia','','Columnas',null,'material','ud',0),
  ('art_r_encimera','forgevia','','Encimera',null,'material','ud',0),
  ('art_r_copete_y_remates','forgevia','','Copete y remates',null,'material','ud',0),
  ('art_r_fregadero','forgevia','','Fregadero',null,'material','ud',0),
  ('art_r_grifo_de_cocina','forgevia','','Grifo de cocina',null,'material','ud',0),
  ('art_r_sifon_y_desague','forgevia','','Sifón y desagüe',null,'material','ud',0),
  ('art_r_tuberias_de_agua_y_accesorios','forgevia','','Tuberías de agua y accesorios',null,'material','ml',0),
  ('art_r_pvc_de_desague','forgevia','','PVC de desagüe',null,'material','ud',0),
  ('art_r_placa_de_cocina','forgevia','','Placa de cocina',null,'material','m²',0),
  ('art_r_horno','forgevia','','Horno',null,'material','ud',0),
  ('art_r_campana_extractor','forgevia','','Campana/extractor',null,'material','ud',0),
  ('art_r_lavavajillas','forgevia','','Lavavajillas',null,'material','ud',0),
  ('art_r_frigorifico','forgevia','','Frigorífico',null,'material','ud',0),
  ('art_r_microondas','forgevia','','Microondas',null,'material','ud',0),
  ('art_r_revestimiento_frontal_de_cocina','forgevia','','Revestimiento/frontal de cocina',null,'material','m²',0),
  ('art_r_material_de_juntas','forgevia','','Material de juntas',null,'material','ud',0),
  ('art_r_silicona','forgevia','','Silicona',null,'material','ud',0),
  ('art_r_enchufes','forgevia','','Enchufes',null,'material','ud',0),
  ('art_r_interruptores','forgevia','','Interruptores',null,'material','ud',0),
  ('art_r_cableado','forgevia','','Cableado',null,'material','ml',0),
  ('art_r_cajas_de_mecanismos','forgevia','','Cajas de mecanismos',null,'material','ud',0),
  ('art_r_cajas_de_derivacion','forgevia','','Cajas de derivación',null,'material','ud',0),
  ('art_r_protecciones_electricas','forgevia','','Protecciones eléctricas',null,'material','ud',0),
  ('art_r_iluminacion_de_techo','forgevia','','Iluminación de techo',null,'material','ud',0),
  ('art_r_iluminacion_bajo_muebles','forgevia','','Iluminación bajo muebles',null,'material','ud',0),
  ('art_r_pintura','forgevia','','Pintura',null,'material','m²',0),
  ('art_r_masilla_y_materiales_de_acabado','forgevia','','Masilla y materiales de acabado',null,'material','ud',0),
  ('art_r_material_de_proteccion_y_demolicion','forgevia','','Material de protección y demolición',null,'material','ud',0),
  ('art_r_sacos_y_gestion_de_residuos','forgevia','','Sacos y gestión de residuos',null,'material','ud',0),
  ('art_r_contenedor','forgevia','','Contenedor',null,'material','ud',0),
  ('art_r_ladrillo','forgevia','','Ladrillo',null,'material','ud',0),
  ('art_r_bloques','forgevia','','Bloques',null,'material','ud',0),
  ('art_r_cemento','forgevia','','Cemento',null,'material','ud',0),
  ('art_r_arena','forgevia','','Arena',null,'material','ud',0),
  ('art_r_yeso','forgevia','','Yeso',null,'material','ud',0),
  ('art_r_pasta_de_agarre','forgevia','','Pasta de agarre',null,'material','ud',0),
  ('art_r_placas_de_pladur','forgevia','','Placas de pladur',null,'material','m²',0),
  ('art_r_perfileria','forgevia','','Perfilería',null,'material','ml',0),
  ('art_r_aislamiento_termico_acustico','forgevia','','Aislamiento térmico/acústico',null,'material','m²',0),
  ('art_r_cintas_y_pastas_de_juntas','forgevia','','Cintas y pastas de juntas',null,'material','ud',0),
  ('art_r_pavimento_ceramico_porcelanico_o_tarima','forgevia','','Pavimento cerámico/porcelánico o tarima',null,'material','m²',0),
  ('art_r_rodapies','forgevia','','Rodapiés',null,'material','ml',0),
  ('art_r_adhesivos','forgevia','','Adhesivos',null,'material','ud',0),
  ('art_r_material_de_rejuntado','forgevia','','Material de rejuntado',null,'material','ud',0),
  ('art_r_material_de_nivelacion','forgevia','','Material de nivelación',null,'material','ud',0),
  ('art_r_puertas_interiores','forgevia','','Puertas interiores',null,'material','ud',0),
  ('art_r_premarcos','forgevia','','Premarcos',null,'material','ud',0),
  ('art_r_manillas_y_herrajes','forgevia','','Manillas y herrajes',null,'material','ud',0),
  ('art_r_armarios','forgevia','','Armarios',null,'material','ud',0),
  ('art_r_imprimacion','forgevia','','Imprimación',null,'material','m²',0),
  ('art_r_masillas','forgevia','','Masillas',null,'material','ud',0),
  ('art_r_selladores','forgevia','','Selladores',null,'material','ud',0),
  ('art_r_material_completo_de_fontaneria','forgevia','','Material completo de fontanería',null,'material','ud',0),
  ('art_r_tuberias_de_agua','forgevia','','Tuberías de agua',null,'material','ml',0),
  ('art_r_desagues_pvc','forgevia','','Desagües PVC',null,'material','ud',0),
  ('art_r_llaves_de_corte','forgevia','','Llaves de corte',null,'material','ud',0),
  ('art_r_colectores','forgevia','','Colectores',null,'material','ud',0),
  ('art_r_sanitarios','forgevia','','Sanitarios',null,'material','ud',0),
  ('art_r_griferias','forgevia','','Griferías',null,'material','ud',0),
  ('art_r_material_electrico_completo','forgevia','','Material eléctrico completo',null,'material','ud',0),
  ('art_r_cuadro_electrico','forgevia','','Cuadro eléctrico',null,'material','ud',0),
  ('art_r_iluminacion','forgevia','','Iluminación',null,'material','ud',0),
  ('art_r_mecanismos','forgevia','','Mecanismos',null,'material','ud',0),
  ('art_r_telecomunicaciones','forgevia','','Telecomunicaciones',null,'material','ud',0),
  ('art_r_material_de_climatizacion','forgevia','','Material de climatización',null,'material','ud',0),
  ('art_r_conductos_tuberias_de_climatizacion','forgevia','','Conductos/tuberías de climatización',null,'material','ml',0),
  ('art_r_rejillas_y_difusores','forgevia','','Rejillas y difusores',null,'material','ud',0),
  ('art_r_material_de_ventilacion','forgevia','','Material de ventilación',null,'material','ud',0),
  ('art_r_termo_caldera_aerotermia','forgevia','','Termo/caldera/aerotermia',null,'material','ud',0),
  ('art_r_ventanas_y_carpinteria_exterior','forgevia','','Ventanas y carpintería exterior',null,'material','ud',0),
  ('art_r_siliconas_espumas_fijaciones_y_consumibles','forgevia','','Siliconas, espumas, fijaciones y consumibles',null,'material','ud',0),
  ('art_r_envolvente_armario_electrico','forgevia','','Envolvente/armario eléctrico',null,'material','ud',0),
  ('art_r_iga','forgevia','','IGA',null,'material','ud',0),
  ('art_r_interruptores_diferenciales','forgevia','','Interruptores diferenciales',null,'material','ud',0),
  ('art_r_magnetotermicos','forgevia','','Magnetotérmicos',null,'material','ud',0),
  ('art_r_protector_contra_sobretensiones','forgevia','','Protector contra sobretensiones',null,'material','ud',0),
  ('art_r_contactores','forgevia','','Contactores',null,'material','ud',0),
  ('art_r_peines_de_conexion','forgevia','','Peines de conexión',null,'material','ud',0),
  ('art_r_borneros','forgevia','','Borneros',null,'material','ud',0),
  ('art_r_cableado_de_diferentes_secciones','forgevia','','Cableado de diferentes secciones',null,'material','ml',0),
  ('art_r_cable_libre_de_halogenos','forgevia','','Cable libre de halógenos',null,'material','ml',0),
  ('art_r_tubo_rigido','forgevia','','Tubo rígido',null,'material','ml',0),
  ('art_r_bandeja_portacables','forgevia','','Bandeja portacables',null,'material','ml',0),
  ('art_r_canaleta','forgevia','','Canaleta',null,'material','ml',0),
  ('art_r_cajas_de_registro','forgevia','','Cajas de registro',null,'material','ud',0),
  ('art_r_conmutadores','forgevia','','Conmutadores',null,'material','ud',0),
  ('art_r_pulsadores','forgevia','','Pulsadores',null,'material','ud',0),
  ('art_r_tomas_industriales','forgevia','','Tomas industriales',null,'material','ud',0),
  ('art_r_lineas_independientes_para_maquinaria','forgevia','','Líneas independientes para maquinaria',null,'material','ml',0),
  ('art_r_lineas_de_climatizacion','forgevia','','Líneas de climatización',null,'material','ml',0),
  ('art_r_linea_de_iluminacion','forgevia','','Línea de iluminación',null,'material','ml',0),
  ('art_r_lineas_de_fuerza','forgevia','','Líneas de fuerza',null,'material','ml',0),
  ('art_r_linea_de_emergencia','forgevia','','Línea de emergencia',null,'material','ml',0),
  ('art_r_alumbrado_normal','forgevia','','Alumbrado normal',null,'material','ud',0),
  ('art_r_alumbrado_de_emergencia','forgevia','','Alumbrado de emergencia',null,'material','ud',0),
  ('art_r_senalizacion_de_salida_emergencia','forgevia','','Señalización de salida/emergencia',null,'material','ud',0),
  ('art_r_detectores_de_presencia','forgevia','','Detectores de presencia',null,'material','ud',0),
  ('art_r_temporizadores','forgevia','','Temporizadores',null,'material','ud',0),
  ('art_r_cable_de_tierra','forgevia','','Cable de tierra',null,'material','ml',0),
  ('art_r_sistema_de_puesta_a_tierra','forgevia','','Sistema de puesta a tierra',null,'material','ud',0),
  ('art_r_regletas_y_bornes','forgevia','','Regletas y bornes',null,'material','ud',0),
  ('art_r_prensaestopas','forgevia','','Prensaestopas',null,'material','ud',0),
  ('art_r_terminales_punteras','forgevia','','Terminales/punteras',null,'material','ud',0),
  ('art_r_bridas_y_fijaciones','forgevia','','Bridas y fijaciones',null,'material','ud',0),
  ('art_r_cable_de_red','forgevia','','Cable de red',null,'material','ml',0),
  ('art_r_tomas_rj45','forgevia','','Tomas RJ45',null,'material','ud',0),
  ('art_r_rack','forgevia','','Rack',null,'material','ud',0),
  ('art_r_material_auxiliar_y_consumibles','forgevia','','Material auxiliar y consumibles',null,'material','ud',0),
  ('art_r_protector_de_sobretensiones','forgevia','','Protector de sobretensiones',null,'material','ud',0),
  ('art_r_diferenciales','forgevia','','Diferenciales',null,'material','ud',0),
  ('art_r_peines_y_borneros','forgevia','','Peines y borneros',null,'material','ud',0),
  ('art_r_cableado_electrico_de_distintas_secciones','forgevia','','Cableado eléctrico de distintas secciones',null,'material','ml',0),
  ('art_r_cruzamientos','forgevia','','Cruzamientos',null,'material','ud',0),
  ('art_r_tomas_de_television','forgevia','','Tomas de televisión',null,'material','ud',0),
  ('art_r_tomas_de_datos_rj45','forgevia','','Tomas de datos/RJ45',null,'material','ud',0),
  ('art_r_tomas_de_telefono','forgevia','','Tomas de teléfono',null,'material','ud',0),
  ('art_r_puntos_de_luz','forgevia','','Puntos de luz',null,'material','ud',0),
  ('art_r_portalamparas_conectores','forgevia','','Portalámparas/conectores',null,'material','ud',0),
  ('art_r_downlights_focos_luminarias','forgevia','','Downlights/focos/luminarias',null,'material','ud',0),
  ('art_r_linea_de_enchufes_generales','forgevia','','Línea de enchufes generales',null,'material','ml',0),
  ('art_r_linea_de_cocina_y_horno','forgevia','','Línea de cocina y horno',null,'material','ml',0),
  ('art_r_linea_de_lavadora','forgevia','','Línea de lavadora',null,'material','ml',0),
  ('art_r_linea_de_lavavajillas','forgevia','','Línea de lavavajillas',null,'material','ml',0),
  ('art_r_linea_de_termo_electrico','forgevia','','Línea de termo eléctrico',null,'material','ml',0),
  ('art_r_linea_de_climatizacion','forgevia','','Línea de climatización',null,'material','ml',0),
  ('art_r_lineas_de_banos_y_auxiliares','forgevia','','Líneas de baños y auxiliares',null,'material','ml',0),
  ('art_r_extractores','forgevia','','Extractores',null,'material','ud',0),
  ('art_r_terminales','forgevia','','Terminales',null,'material','ud',0),
  ('art_r_bridas','forgevia','','Bridas',null,'material','ud',0),
  ('art_r_grapas_y_fijaciones','forgevia','','Grapas y fijaciones',null,'material','ud',0),
  ('art_r_material_de_conexion_y_consumibles','forgevia','','Material de conexión y consumibles',null,'material','ud',0)
on conflict (id) do nothing;

insert into partidas (id, tenant_id, nombre, unidad, descripcion, componentes) values
  ('pack_r_bano_tipico','forgevia','Baño típico','ud','Materiales típicos de: Baño típico.','[{"id":"c0","articuloId":"art_r_plato_de_ducha","cantidad":1},{"id":"c1","articuloId":"art_r_mampara","cantidad":1},{"id":"c2","articuloId":"art_r_valvula_desague_de_ducha","cantidad":1},{"id":"c3","articuloId":"art_r_griferia_de_ducha","cantidad":1},{"id":"c4","articuloId":"art_r_columna_o_conjunto_de_ducha","cantidad":1},{"id":"c5","articuloId":"art_r_inodoro","cantidad":1},{"id":"c6","articuloId":"art_r_mueble_de_lavabo","cantidad":1},{"id":"c7","articuloId":"art_r_lavabo","cantidad":1},{"id":"c8","articuloId":"art_r_grifo_de_lavabo","cantidad":1},{"id":"c9","articuloId":"art_r_espejo","cantidad":1},{"id":"c10","articuloId":"art_r_sifon_y_valvula_de_lavabo","cantidad":1},{"id":"c11","articuloId":"art_r_tuberia_multicapa_ppr_y_accesorios","cantidad":1},{"id":"c12","articuloId":"art_r_tuberia_pvc_para_desagues_y_accesorios","cantidad":1},{"id":"c13","articuloId":"art_r_llaves_de_escuadra","cantidad":1},{"id":"c14","articuloId":"art_r_alicatado_azulejo","cantidad":1},{"id":"c15","articuloId":"art_r_pavimento","cantidad":1},{"id":"c16","articuloId":"art_r_adhesivo_cementoso","cantidad":1},{"id":"c17","articuloId":"art_r_mortero","cantidad":1},{"id":"c18","articuloId":"art_r_lechada_material_de_juntas","cantidad":1},{"id":"c19","articuloId":"art_r_sistema_de_impermeabilizacion","cantidad":1},{"id":"c20","articuloId":"art_r_silicona_sanitaria","cantidad":1},{"id":"c21","articuloId":"art_r_perfiles_y_remates","cantidad":1},{"id":"c22","articuloId":"art_r_pladur_hidrofugo","cantidad":1},{"id":"c23","articuloId":"art_r_perfileria_de_pladur","cantidad":1},{"id":"c24","articuloId":"art_r_tornilleria","cantidad":1},{"id":"c25","articuloId":"art_r_masilla_y_cinta","cantidad":1},{"id":"c26","articuloId":"art_r_downlights_focos","cantidad":1},{"id":"c27","articuloId":"art_r_interruptores_y_mecanismos","cantidad":1},{"id":"c28","articuloId":"art_r_cableado_electrico","cantidad":1},{"id":"c29","articuloId":"art_r_tubo_corrugado","cantidad":1},{"id":"c30","articuloId":"art_r_cajas_electricas","cantidad":1},{"id":"c31","articuloId":"art_r_extractor_de_bano","cantidad":1},{"id":"c32","articuloId":"art_r_pintura_para_techo","cantidad":1}]'::jsonb),
  ('pack_r_cocina','forgevia','Cocina','ud','Materiales típicos de: Cocina.','[{"id":"c0","articuloId":"art_r_muebles_bajos","cantidad":1},{"id":"c1","articuloId":"art_r_muebles_altos","cantidad":1},{"id":"c2","articuloId":"art_r_columnas","cantidad":1},{"id":"c3","articuloId":"art_r_encimera","cantidad":1},{"id":"c4","articuloId":"art_r_copete_y_remates","cantidad":1},{"id":"c5","articuloId":"art_r_fregadero","cantidad":1},{"id":"c6","articuloId":"art_r_grifo_de_cocina","cantidad":1},{"id":"c7","articuloId":"art_r_sifon_y_desague","cantidad":1},{"id":"c8","articuloId":"art_r_llaves_de_escuadra","cantidad":1},{"id":"c9","articuloId":"art_r_tuberias_de_agua_y_accesorios","cantidad":1},{"id":"c10","articuloId":"art_r_pvc_de_desague","cantidad":1},{"id":"c11","articuloId":"art_r_placa_de_cocina","cantidad":1},{"id":"c12","articuloId":"art_r_horno","cantidad":1},{"id":"c13","articuloId":"art_r_campana_extractor","cantidad":1},{"id":"c14","articuloId":"art_r_lavavajillas","cantidad":1},{"id":"c15","articuloId":"art_r_frigorifico","cantidad":1},{"id":"c16","articuloId":"art_r_microondas","cantidad":1},{"id":"c17","articuloId":"art_r_revestimiento_frontal_de_cocina","cantidad":1},{"id":"c18","articuloId":"art_r_pavimento","cantidad":1},{"id":"c19","articuloId":"art_r_adhesivo_cementoso","cantidad":1},{"id":"c20","articuloId":"art_r_material_de_juntas","cantidad":1},{"id":"c21","articuloId":"art_r_silicona","cantidad":1},{"id":"c22","articuloId":"art_r_enchufes","cantidad":1},{"id":"c23","articuloId":"art_r_interruptores","cantidad":1},{"id":"c24","articuloId":"art_r_cableado","cantidad":1},{"id":"c25","articuloId":"art_r_tubo_corrugado","cantidad":1},{"id":"c26","articuloId":"art_r_cajas_de_mecanismos","cantidad":1},{"id":"c27","articuloId":"art_r_cajas_de_derivacion","cantidad":1},{"id":"c28","articuloId":"art_r_protecciones_electricas","cantidad":1},{"id":"c29","articuloId":"art_r_iluminacion_de_techo","cantidad":1},{"id":"c30","articuloId":"art_r_iluminacion_bajo_muebles","cantidad":1},{"id":"c31","articuloId":"art_r_pintura","cantidad":1},{"id":"c32","articuloId":"art_r_masilla_y_materiales_de_acabado","cantidad":1}]'::jsonb),
  ('pack_r_reforma_completa','forgevia','Reforma completa','ud','Materiales típicos de: Reforma completa.','[{"id":"c0","articuloId":"art_r_material_de_proteccion_y_demolicion","cantidad":1},{"id":"c1","articuloId":"art_r_sacos_y_gestion_de_residuos","cantidad":1},{"id":"c2","articuloId":"art_r_contenedor","cantidad":1},{"id":"c3","articuloId":"art_r_ladrillo","cantidad":1},{"id":"c4","articuloId":"art_r_bloques","cantidad":1},{"id":"c5","articuloId":"art_r_mortero","cantidad":1},{"id":"c6","articuloId":"art_r_cemento","cantidad":1},{"id":"c7","articuloId":"art_r_arena","cantidad":1},{"id":"c8","articuloId":"art_r_yeso","cantidad":1},{"id":"c9","articuloId":"art_r_pasta_de_agarre","cantidad":1},{"id":"c10","articuloId":"art_r_placas_de_pladur","cantidad":1},{"id":"c11","articuloId":"art_r_pladur_hidrofugo","cantidad":1},{"id":"c12","articuloId":"art_r_perfileria","cantidad":1},{"id":"c13","articuloId":"art_r_aislamiento_termico_acustico","cantidad":1},{"id":"c14","articuloId":"art_r_tornilleria","cantidad":1},{"id":"c15","articuloId":"art_r_cintas_y_pastas_de_juntas","cantidad":1},{"id":"c16","articuloId":"art_r_pavimento_ceramico_porcelanico_o_tarima","cantidad":1},{"id":"c17","articuloId":"art_r_rodapies","cantidad":1},{"id":"c18","articuloId":"art_r_adhesivos","cantidad":1},{"id":"c19","articuloId":"art_r_material_de_rejuntado","cantidad":1},{"id":"c20","articuloId":"art_r_material_de_nivelacion","cantidad":1},{"id":"c21","articuloId":"art_r_puertas_interiores","cantidad":1},{"id":"c22","articuloId":"art_r_premarcos","cantidad":1},{"id":"c23","articuloId":"art_r_manillas_y_herrajes","cantidad":1},{"id":"c24","articuloId":"art_r_armarios","cantidad":1},{"id":"c25","articuloId":"art_r_pintura","cantidad":1},{"id":"c26","articuloId":"art_r_imprimacion","cantidad":1},{"id":"c27","articuloId":"art_r_masillas","cantidad":1},{"id":"c28","articuloId":"art_r_selladores","cantidad":1},{"id":"c29","articuloId":"art_r_material_completo_de_fontaneria","cantidad":1},{"id":"c30","articuloId":"art_r_tuberias_de_agua","cantidad":1},{"id":"c31","articuloId":"art_r_desagues_pvc","cantidad":1},{"id":"c32","articuloId":"art_r_llaves_de_corte","cantidad":1},{"id":"c33","articuloId":"art_r_colectores","cantidad":1},{"id":"c34","articuloId":"art_r_sanitarios","cantidad":1},{"id":"c35","articuloId":"art_r_griferias","cantidad":1},{"id":"c36","articuloId":"art_r_material_electrico_completo","cantidad":1},{"id":"c37","articuloId":"art_r_cuadro_electrico","cantidad":1},{"id":"c38","articuloId":"art_r_iluminacion","cantidad":1},{"id":"c39","articuloId":"art_r_mecanismos","cantidad":1},{"id":"c40","articuloId":"art_r_telecomunicaciones","cantidad":1},{"id":"c41","articuloId":"art_r_material_de_climatizacion","cantidad":1},{"id":"c42","articuloId":"art_r_conductos_tuberias_de_climatizacion","cantidad":1},{"id":"c43","articuloId":"art_r_rejillas_y_difusores","cantidad":1},{"id":"c44","articuloId":"art_r_material_de_ventilacion","cantidad":1},{"id":"c45","articuloId":"art_r_termo_caldera_aerotermia","cantidad":1},{"id":"c46","articuloId":"art_r_ventanas_y_carpinteria_exterior","cantidad":1},{"id":"c47","articuloId":"art_r_siliconas_espumas_fijaciones_y_consumibles","cantidad":1}]'::jsonb),
  ('pack_r_electricidad_de_local','forgevia','Electricidad de local','ud','Materiales típicos de: Electricidad de local.','[{"id":"c0","articuloId":"art_r_cuadro_electrico","cantidad":1},{"id":"c1","articuloId":"art_r_envolvente_armario_electrico","cantidad":1},{"id":"c2","articuloId":"art_r_iga","cantidad":1},{"id":"c3","articuloId":"art_r_interruptores_diferenciales","cantidad":1},{"id":"c4","articuloId":"art_r_magnetotermicos","cantidad":1},{"id":"c5","articuloId":"art_r_protector_contra_sobretensiones","cantidad":1},{"id":"c6","articuloId":"art_r_contactores","cantidad":1},{"id":"c7","articuloId":"art_r_peines_de_conexion","cantidad":1},{"id":"c8","articuloId":"art_r_borneros","cantidad":1},{"id":"c9","articuloId":"art_r_cableado_de_diferentes_secciones","cantidad":1},{"id":"c10","articuloId":"art_r_cable_libre_de_halogenos","cantidad":1},{"id":"c11","articuloId":"art_r_tubo_corrugado","cantidad":1},{"id":"c12","articuloId":"art_r_tubo_rigido","cantidad":1},{"id":"c13","articuloId":"art_r_bandeja_portacables","cantidad":1},{"id":"c14","articuloId":"art_r_canaleta","cantidad":1},{"id":"c15","articuloId":"art_r_cajas_de_derivacion","cantidad":1},{"id":"c16","articuloId":"art_r_cajas_de_mecanismos","cantidad":1},{"id":"c17","articuloId":"art_r_cajas_de_registro","cantidad":1},{"id":"c18","articuloId":"art_r_enchufes","cantidad":1},{"id":"c19","articuloId":"art_r_interruptores","cantidad":1},{"id":"c20","articuloId":"art_r_conmutadores","cantidad":1},{"id":"c21","articuloId":"art_r_pulsadores","cantidad":1},{"id":"c22","articuloId":"art_r_tomas_industriales","cantidad":1},{"id":"c23","articuloId":"art_r_lineas_independientes_para_maquinaria","cantidad":1},{"id":"c24","articuloId":"art_r_lineas_de_climatizacion","cantidad":1},{"id":"c25","articuloId":"art_r_linea_de_iluminacion","cantidad":1},{"id":"c26","articuloId":"art_r_lineas_de_fuerza","cantidad":1},{"id":"c27","articuloId":"art_r_linea_de_emergencia","cantidad":1},{"id":"c28","articuloId":"art_r_alumbrado_normal","cantidad":1},{"id":"c29","articuloId":"art_r_alumbrado_de_emergencia","cantidad":1},{"id":"c30","articuloId":"art_r_senalizacion_de_salida_emergencia","cantidad":1},{"id":"c31","articuloId":"art_r_detectores_de_presencia","cantidad":1},{"id":"c32","articuloId":"art_r_temporizadores","cantidad":1},{"id":"c33","articuloId":"art_r_cable_de_tierra","cantidad":1},{"id":"c34","articuloId":"art_r_sistema_de_puesta_a_tierra","cantidad":1},{"id":"c35","articuloId":"art_r_regletas_y_bornes","cantidad":1},{"id":"c36","articuloId":"art_r_prensaestopas","cantidad":1},{"id":"c37","articuloId":"art_r_terminales_punteras","cantidad":1},{"id":"c38","articuloId":"art_r_bridas_y_fijaciones","cantidad":1},{"id":"c39","articuloId":"art_r_cable_de_red","cantidad":1},{"id":"c40","articuloId":"art_r_tomas_rj45","cantidad":1},{"id":"c41","articuloId":"art_r_rack","cantidad":1},{"id":"c42","articuloId":"art_r_material_auxiliar_y_consumibles","cantidad":1}]'::jsonb),
  ('pack_r_electricidad_de_piso','forgevia','Electricidad de piso','ud','Materiales típicos de: Electricidad de piso.','[{"id":"c0","articuloId":"art_r_cuadro_electrico","cantidad":1},{"id":"c1","articuloId":"art_r_iga","cantidad":1},{"id":"c2","articuloId":"art_r_protector_de_sobretensiones","cantidad":1},{"id":"c3","articuloId":"art_r_diferenciales","cantidad":1},{"id":"c4","articuloId":"art_r_magnetotermicos","cantidad":1},{"id":"c5","articuloId":"art_r_peines_y_borneros","cantidad":1},{"id":"c6","articuloId":"art_r_cableado_electrico_de_distintas_secciones","cantidad":1},{"id":"c7","articuloId":"art_r_cable_de_tierra","cantidad":1},{"id":"c8","articuloId":"art_r_tubo_corrugado","cantidad":1},{"id":"c9","articuloId":"art_r_cajas_de_registro","cantidad":1},{"id":"c10","articuloId":"art_r_cajas_de_mecanismos","cantidad":1},{"id":"c11","articuloId":"art_r_enchufes","cantidad":1},{"id":"c12","articuloId":"art_r_interruptores","cantidad":1},{"id":"c13","articuloId":"art_r_conmutadores","cantidad":1},{"id":"c14","articuloId":"art_r_cruzamientos","cantidad":1},{"id":"c15","articuloId":"art_r_tomas_de_television","cantidad":1},{"id":"c16","articuloId":"art_r_tomas_de_datos_rj45","cantidad":1},{"id":"c17","articuloId":"art_r_tomas_de_telefono","cantidad":1},{"id":"c18","articuloId":"art_r_puntos_de_luz","cantidad":1},{"id":"c19","articuloId":"art_r_portalamparas_conectores","cantidad":1},{"id":"c20","articuloId":"art_r_downlights_focos_luminarias","cantidad":1},{"id":"c21","articuloId":"art_r_linea_de_iluminacion","cantidad":1},{"id":"c22","articuloId":"art_r_linea_de_enchufes_generales","cantidad":1},{"id":"c23","articuloId":"art_r_linea_de_cocina_y_horno","cantidad":1},{"id":"c24","articuloId":"art_r_linea_de_lavadora","cantidad":1},{"id":"c25","articuloId":"art_r_linea_de_lavavajillas","cantidad":1},{"id":"c26","articuloId":"art_r_linea_de_termo_electrico","cantidad":1},{"id":"c27","articuloId":"art_r_linea_de_climatizacion","cantidad":1},{"id":"c28","articuloId":"art_r_lineas_de_banos_y_auxiliares","cantidad":1},{"id":"c29","articuloId":"art_r_extractores","cantidad":1},{"id":"c30","articuloId":"art_r_regletas_y_bornes","cantidad":1},{"id":"c31","articuloId":"art_r_terminales","cantidad":1},{"id":"c32","articuloId":"art_r_bridas","cantidad":1},{"id":"c33","articuloId":"art_r_grapas_y_fijaciones","cantidad":1},{"id":"c34","articuloId":"art_r_material_de_conexion_y_consumibles","cantidad":1}]'::jsonb)
on conflict (id) do nothing;
